remote_theme: volny/creative-theme-jekyll
#theme: jekyll-theme-cayman
title: Women Techmakers Silesia
description: Website for Women Techmakers Silesia – program for empowering and supporting women in IT
